### ISSUE TITLE
2. Python 数据结构--1.2.5.2 字典练习

### ISSUE THREAD

**Issue by fanxting** [datawhalechina/learn-python-the-smart-way#11]
![image](https://user-images.githubusercontent.com/15911131/187373753-6f7c689a-064c-4a00-aeb6-2d798bc7784c.png)

根据这个循环， 输入如下时：
nums = [2, 1, 3, 5]
target = 4
输出为：
[2, 2]

是否不对？

**Comment by anine09** [comment]
我来为你解释下这段代码的运行逻辑。

 `check_sum` 函数的逻辑我就略过不解释了，请参考 [1. Python 安装及基本语法 1.1.3.2 函数](https://github.com/datawhalechina/learn-python-the-smart-way/blob/main/1.%20Python%20%E5%AE%89%E8%A3%85%E5%8F%8A%E5%9F%BA%E6%9C%AC%E8%AF%AD%E6%B3%95.ipynb)。

`twosum` 函数里有个 `finded =   False`，我猜测 @ChuanyuXue 可能是希望设置一个 Flag，在遍历到想要的答案后，将 `finded` 的值改为 `True`，以结束循环。

下面的两层 `for` 循环，是为了遍历所有 `nums` 里的两两组合，例如 `a[0]` 和  `b[0]` 组成的 `[2,2]`、`a[1]` 和 `b[0]` 组成的 `[2,7]`……

如果 `a[x] + b[y] == target` 的话，就返回对应的 `a[x]` 和 `b[y]` 的值。**但是，这段代码只会返回第一个找到的结果，就结束函数运行，而不是返回所有结果**，如果对函数的结束条件不熟悉的话，理解这个代码会有些困难。所有我认为这个题目并不适合初学者，我们正在改进第二版教程，敬请关注。

如果有解决你的疑惑，请关闭 Issue。如果仍有疑惑，可以通过邮件联系我 [epsilon_luoo@outlook.com](mailto:epsilon_luoo@outlook.com)

我们很快就会开始发布第二版教程，欢迎关注并提建议。

**Comment by fanxting** [comment]
我知道这段代码的意思

我可能没表达清楚我的意思，题目如下：
![image](https://user-images.githubusercontent.com/15911131/188764795-69dbfedf-f924-45e0-bcc4-27c0b7651f3a.png)

题目说的是找出两个整数， 此处的“两个”我理解的是不同的下标的俩元素;如您举的例子， a[x] + b[y] == target， x！=y

而nums = [2, 1, 3, 5]， 输出的是[2, 2]也就是，nums[0], nums[0]

不好意思
打扰了！！！！

**Comment by anine09** [comment]
没事没事的，我们很乐于为同学们解答疑惑。应该是我们在题目中的描述容易产生歧义，后面我们也会注重这个方面，争取不再犯类似错误。
