### ISSUE TITLE
1. Python 安装及基本语法.ipynb 无论是github还是google Colab都无法打开

### ISSUE THREAD

**Issue by devilzyl** [datawhalechina/learn-python-the-smart-way#4]
1. Python 安装及基本语法.ipynb 无论是github还是google Colab都无法打开，其余三个是正常的

**Comment by Sm1les** [comment]
@devilzyl 你下载到本地试试

**Comment by ChuanyuXue** [comment]
@devilzyl @Sm1les 抱歉，上次的merge对ipynb的修改出现了问题，现文件1已版本回退。
